apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
spec:
  selector:
    matchLabels:
      app: back-end
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - name: back-end
          image: mrstjch/todo-backend
          env:
            - name: MONGODB_URL
              value: "mongodb+srv://satya:satya123@todo.kreblnz.mongodb.net/"
          ports:
            - containerPort: 3001
              name: back-end
