apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
spec:
  selector:
    matchLabels:
      app: back-end
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - name: back-end
          image: mrstjch/todo-backend
          env:
            - name: MONGODB_URL
              value: mongodb://admin:password123@mongodb-svc/
          resources:
            requests:
              cpu: "200m"
              memory: "428Mi"
            limits:
              memory: "528Mi"
              cpu: "1000m"
          ports:
            - containerPort: 3001
              name: back-end
