apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-end
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: back-end
    spec:
      containers:
        - name: back-end
          image: mrstjch/todo-backend
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: backend-env-config
                  key: MONGODB_URI
          envFrom:
            - configMapRef:
                name: backend-config
            - configMapRef:
                name: backend-env-config
            - secretRef:
                name: backend-secrets
