apiVersion: v1
kind: Service
metadata:
  name: back-end-svc
  labels:
    app: back-end
spec:
  type: NodePort
  selector:
    app: back-end
  ports:
  - name: back-end-svc
    port: 3001
    targetPort: 3001