namespace: node-app
# commonLabels:
#   app: node-app
resources:
  - ../../base/apps/be
  - ../../base/apps/fe
  - ../../base/apps/mongo
  - be-ingress.yaml
  - fe-ingress.yaml
  - be-cm.yaml
  - argo-svc-ingress.yml
patchesStrategicMerge:
  - be-deploy.yaml
  - fe-deploy.yaml
  - argo-deploy.yml
images:
  - name: mrstjch/todo-frontend
    newTag: latest
  - name: mrstjch/todo-backend
    newTag: 1.0.2
