apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-volume
  namespace: node-app
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /data/db