apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-volume-claim
spec:
  accessModes:
  - ReadWriteOnce  # Adjust to ReadWriteMany if needed for your use case
  resources:
    requests:
      storage: 1Gi  # Adjust storage size based on your requirements
